name: CI
on: [push]

jobs:
    ubuntu-20_04-gcc:
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                build: [Debug, Release]

        steps:
            - name: Clone
              uses: actions/checkout@v1
              with:
                  submodules: true

            - name: Dependencies
              run: sudo apt-get update && sudo apt-get install libncurses5-dev libcurl4-openssl-dev

            - name: Configure
              run: cmake . -DCMAKE_BUILD_TYPE=${{ matrix.build }}

            - name: Build
              run: make

    ubuntu-18_04-clang:
        runs-on: ubuntu-18.04

        strategy:
            matrix:
                build: [Debug, Release]

        steps:
            - name: Clone
              uses: actions/checkout@v1
              with:
                  submodules: true

            - name: Dependencies
              run: sudo apt-get update && sudo apt-get install libncurses5-dev libcurl4-openssl-dev

            - name: Configure
              run: cmake . -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang

            - name: Build
              run: make

    macOS-latest:
        runs-on: macOS-latest

        strategy:
            matrix:
                build: [Debug, Release]

        steps:
            - name: Clone
              uses: actions/checkout@v1
              with:
                  submodules: true

            - name: Dependencies
              run: echo "tmp"

            - name: Configure
              run: cmake . -DCMAKE_BUILD_TYPE=${{ matrix.build }}

            - name: Build
              run: make
