name: Ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: mkdir build && cd build
    - name: cmake
      run: cmake ..
    - name: make
      run: make
